# Run clang-tidy
name: Clang-tidy

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Update git submodules
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --init --recursive
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@5f6a5d643cb8ab44f57c8d16a78f53b8ba75e13a
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build/'
        excludedirs: 'vendored/'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: '-DSDL_UNIX_CONSOLE_BUILD=ON'