name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions: {}

jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --init --recursive
      - name: Setup to run clang-tidy
        run: |
          sudo apt install -y clang-tidy
          sudo apt install -y cmake
          cmake -DCMAKE_BUILD_TYPE=Debug -DSDL_UNIX_CONSOLE_BUILD=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build/
      - name: Running clang-tidy
        run: |
          clang-tidy -p build/ src/* include/*

  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CPP: false
          VALIDATE_NATURAL_LANGUAGE: false
